Update getting_started.rst
hestiacp/hestiacp-docs pull request #40
Opened 2022-06-23 20:48 UTC by V4M0N0S

First time editing, lets take a look.

2022-06-23 20:50 UTC, jaapmarcus commented on getting_started.rst
>  - Debian 11, 10 or 9
Remove Debian 9 it goes EOL next month

2022-06-23 20:51 UTC, jaapmarcus requested changes
See remark

2022-06-24 05:50 UTC, V4M0N0S commented
Done: https://github.com/hestiacp/hestiacp-docs/pull/40/commits/54862436d24db58ef1035063790810eece09c895

2022-06-24 05:50 UTC, jaapmarcus approved these changes

2022-06-24 05:50 UTC, merged